version: '3.8'

services:
  php-app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3206:80"
    volumes:
      - ../build:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quickpay
      MYSQL_USER: quickpay
      MYSQL_PASSWORD: quickpay123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 