version: '3.8'

services:
  php-app:
    build: .
    ports:
      - "3206:80"
    volumes:
      - ../build:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quickpay
      MYSQL_USER: quickpay
      MYSQL_PASSWORD: quickpay123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: quickpay
      PMA_PASSWORD: quickpay123
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: 